### ISSUE TITLE
Run  Benchmark nullpointer error

### ISSUE THREAD

**Issue by DioCin** [ldbc/ldbc_graphalytics#168]
Hi,

When I run test Benchmark ,I met some  exception.

> [zc@centos6 graphalytics-1.0.0-graphx-0.2-SNAPSHOT]$ ./bin/sh/run-benchmark.sh 
Using HADOOP_HOME=/home/zc/dy/hadoop-2.7.7
08:30 [INFO ] Initializing Benchmark Suite.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/zc/dy/benchmarkForldbc/graphalytics-1.0.0-graphx-0.2-SNAPSHOT/lib/graphalytics-platforms-graphx-0.2-SNAPSHOT-default.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/zc/dy/hadoop-2.7.7/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
08:30 [INFO ] Loading Benchmark...
08:30 [INFO ] Imported 1 graph(s): [example-undirected].
08:30 [INFO ] Failed to import 29 graph(s): [dota-league, com-friendster, twitter_mpi, graph500-22, graph500-23, graph500-24, graph500-25, graph500-26, datagen-7_5-fb, datagen-7_6-fb, datagen-7_7-zf, datagen-7_8-zf, datagen-7_9-fb, datagen-8_0-fb, datagen-8_1-fb, datagen-8_2-zf, datagen-8_3-zf, datagen-8_4-fb, datagen-8_5-fb, datagen-8_6-fb, datagen-8_7-zf, datagen-8_8-zf, datagen-8_9-fb, datagen-9_0-fb, datagen-9_1-fb, datagen-9_2-zf, datagen-9_3-zf, datagen-9_4-fb, example-directed].
Exception in thread "main" java.lang.NullPointerException
        at science.atlarge.graphalytics.domain.benchmark.Benchmark.verifyGraphInfo(Benchmark.java:179)
        at science.atlarge.graphalytics.domain.benchmark.TestBenchmark.setupExperiments(TestBenchmark.java:108)
        at science.atlarge.graphalytics.domain.benchmark.TestBenchmark.setup(TestBenchmark.java:62)
        at science.atlarge.graphalytics.execution.BenchmarkLoader.parse(BenchmarkLoader.java:107)
        at science.atlarge.graphalytics.BenchmarkSuite.main(BenchmarkSuite.java:72)

Another question,when i run benchmark, can I choose the graph platform's partitioning strategy？

**Comment by amusaafir** [comment]
Hello,

The test benchmark requires that you've downloaded the _example-directed_ and _example-undirected_ datasets. In your case, it seems that the _example-directed_ dataset is missing. 
Side note: since you are trying to run GraphX, we expect to have it implemented in the [Graphalytics installer](https://graphalytics.org/software) by the end of this week.

It is currently not possible to select a partitioning strategy through the benchmark properties. However, you could manually modify the platform and/or driver accordingly to achieve this.

If you require any further information, let us know.

**Comment by DioCin** [comment]
Thanks. 
After I add example-directed dataset, I run the test benchmark.
However ,I met error:

> 04:15 [INFO ] ============= Benchmark r764459 [1/12] =============
04:15 [INFO ] Benchmark specification: [BenchmarkRun [r764459, SSSP[src=1, prop=weight], example-directed, timeout=600s]]
04:15 [INFO ] Benchmark configuration: [output=enabled, validation=enabled]
04:15 [INFO ] Log directory: [report/181204-041534-GRAPHX-report-TEST/log/r764459-SSSP-example-directed]
04:15 [INFO ] Input file (vertex): [/home/zc/dy/ldbc/dataset/graphS/test/example-directed.v]
04:15 [INFO ] Input file (edge): [/home/zc/dy/ldbc/dataset/graphS/test/example-directed.e]
04:15 [INFO ] Output directory: [/home/zc/dy/ldbc/output/r764459-SSSP-example-directed]
04:15 [INFO ] Validation directory: [/home/zc/dy/ldbc/dataset/graphS/test/example-directed-SSSP]
04:15 [INFO ] 
04:15 [INFO ] The preparation for the benchmark succeed (if needed).
04:15 [INFO ] The benchmark runner becomes ready within 3 seconds.
04:15 [ERROR] A benchmark failure (EXE) is caught by the runner.
04:15 [ERROR] Failed to find any yarn application ids in the driver log.
04:15 [WARN ] Terminating runner process forcibly.
04:15 [WARN ] Terminating process 20653 focibly.
04:15 [WARN ] Executing command "kill -9 20653"
04:15 [ERROR] Failed to kill runner process.
04:15 [INFO ] The benchmark run is sucessfully terminated.
04:15 [INFO ] Benchmark r764459is failed ([EXE, MET]), T_l=2.771s, T_m=nan, T_p=nan.

I don't know what is" Failed to find any yarn application ids in the driver log" mean.
I Add yarn_conf_dir in spark env.sh .
So  I don't know  where cause the error.

**Comment by DioCin** [comment]
When I try to run giraph, I found the same error.

>06:23 [INFO ] ============= Benchmark r517745 [1/12] =============
06:23 [INFO ] Benchmark specification: [BenchmarkRun [r517745, BFS[src=1], example-directed, timeout=600s]]
06:23 [INFO ] Benchmark configuration: [output=enabled, validation=enabled]
06:23 [INFO ] Log directory: [report/181204-062335-GIRAPH-report-TEST/log/r517745-BFS-example-directed]
06:23 [INFO ] Input file (vertex): [/home/zc/dy/ldbc/dataset/graphS/test/example-directed.v]
06:23 [INFO ] Input file (edge): [/home/zc/dy/ldbc/dataset/graphS/test/cache/example-directed.e]
06:23 [INFO ] Output directory: [/home/zc/dy/ldbc/outputforGiraph/r517745-BFS-example-directed]
06:23 [INFO ] Validation directory: [/home/zc/dy/ldbc/dataset/graphS/test/example-directed-BFS]
06:23 [INFO ] 
06:23 [INFO ] The preparation for the benchmark succeed (if needed).
06:23 [INFO ] The benchmark runner becomes ready within 3 seconds.
06:23 [ERROR] A benchmark failure (EXE) is caught by the runner.
06:23 [ERROR] Failed to find any yarn application ids in the driver log.
06:23 [WARN ] Terminating runner process forcibly.
06:23 [WARN ] Terminating process 22776 focibly.
06:23 [WARN ] Executing command "kill -9 22776"
06:23 [ERROR] Failed to kill runner process.

**Comment by amusaafir** [comment]
Assuming that you've used the Graphalytics installer to set up the Giraph benchmark, this is likely caused by some incorrect Hadoop configuration.

Can you post the settings specified in the `config/platform.properties` file? In addition, how many machines (including master) with Hadoop are you actually using?

Furthermore, is there any additional information logged in `report/{YOUR_BENCHMARK_FOLDER}/log`? Specifically, in the `benchmark-full.log` file and the specific benchmark run folder, e.g., `log/{RUN_ID}-PR-{DATASET}/platform/`

**Comment by DioCin** [comment]
Actually，I use the 5 machines ，one master 4 slaves。I found the error :the executor memory is above the max threshold. After I change the executor memory, it can run .

In my cluster environment, i built a spark cluster. The version of spark is 2.3.1。But when the benchmark run ，I look the port 8088. When I tracing the application ,the spark version is 1.6.0. 
And I can't see anything in my spark master UI in port 8080.
Can graphalytics specify the spark version？
In the platform.properties ,I found that it doesn't configure the spark home.

**Comment by DioCin** [comment]
I want to run graphalytics benchmark to compare the performance of giraph and graphx.
In my my cluster environment,I have hadoop distribute environment. 
Hadoop Version 2.7.7  5 machines  1 master 4 slaves.
Also ,I have distributed environment。
Spark Version 2.3.1  5 machines  1 master 4 slaves.

Question 1: Can graphalytics specify the spark version?  When I  run  graphx test benchmark, I saw  the spark version is 1.6.0.  I can't see anyting in my  running spark  master ui. 

Question 2: When I run giraph test benchmark ,I found error;
the log is :

> science.atlarge.graphalytics.execution.PlatformExecutionException: Giraph job failed with exception: 
        at science.atlarge.graphalytics.giraph.GiraphPlatform.run(GiraphPlatform.java:256) ~[graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at science.atlarge.graphalytics.execution.BenchmarkRunner.run(BenchmarkRunner.java:113) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at science.atlarge.graphalytics.execution.RunnerService.onReceive(RunnerService.java:148) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at `akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)` [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]

>Caused by: java.lang.IllegalArgumentException: checkLocalJobRunnerConfiguration: When using LocalJobRunner, must have only one worker since only 1 task at a time!
        at org.apache.giraph.job.GiraphJob.checkLocalJobRunnerConfiguration(GiraphJob.java:162) ~[graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at org.apache.giraph.job.GiraphJob.run(GiraphJob.java:236) ~[graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at science.atlarge.graphalytics.giraph.GiraphJob.run(GiraphJob.java:233) ~[graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70) ~[hadoop-common-2.7.7.jar:?]
        at science.atlarge.graphalytics.giraph.GiraphPlatform.run(GiraphPlatform.java:244) ~[graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        ... 14 more

My giraph platform properties：

>#The platform
platform.name = Giraph
platform.acronym = giraph
platform.version = 1.2.0
platform.link = https://github.com/apache/giraph

#Address of ZooKeeper deployment (required)
platform.giraph.zoo-keeper-address: centos6:2181,centos7:2181,centos8:2181,centos9:2181,centos10:2181

#Number of Giraph workers (default: 1)
platform.giraph.job.worker-count: 4

#Size of the total memory used per Giraph worker in MB (default: 1280)
platform.giraph.job.memory-size: 4096

#Size of the heap used per Giraph worker in MB, rounded down to the nearest GB by Giraph (default: 1024)
platform.giraph.job.heap-size: 2048

#Number of cores per Giraph worker (default: 1)
platform.giraph.job.worker-cores: 6

#Root directory of Hadoop framework, i.e. HADOOP_HOME (required)
platform.hadoop.home: /home/zc/dy/hadoop-2.7.7

#Directory on HDFS to store all input and output of Graphalytics jobs in
platform.hadoop.hdfs.directory: /ldbc/giraph

#Options starting of the form "platform.giraph.options.X" are passed on to Giraph as "giraph.X". For example:
#platform.giraph.options.numComputeThreads: 4
#platform.giraph.options.dns.namesever: default
#platform.giraph.options.preferIP: false
#platform.giraph.options.dns.interface: ib0
#platform.giraph.options.userPartitionCount: 4

I don't know where cause the error .My worker count is set 4.

**Comment by DioCin** [comment]
Hi @amusaafir .
I want to run graphalytics benchmark to compare the performance of giraph and graphx.
In my my cluster environment,I have hadoop distribute environment.
Hadoop Version 2.7.7 5 machines 1 master 4 slaves.
Also ,I have spark distributed environment。
Spark Version 2.3.1 5 machines 1 master 4 slaves.

Question 1: When I configurate the graphx platform properties ,i found it only configure the hadoop home. Why don't I need to configure spark home？ And When I run  Graphx test benchmark. I found  I can find the job in hadoop yarn ui, but I can't see job in my spark ui. I want to know why ? Does the benchmark job is a spark job? 
Question 2: When I run giraph test benchmark ,I found error;
the log is :

> science.atlarge.graphalytics.execution.PlatformExecutionException: Giraph job failed with exception:
at science.atlarge.graphalytics.giraph.GiraphPlatform.run(GiraphPlatform.java:256) ~[graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at science.atlarge.graphalytics.execution.BenchmarkRunner.run(BenchmarkRunner.java:113) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at science.atlarge.graphalytics.execution.RunnerService.onReceive(RunnerService.java:148) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at akka.actor.Actor$class.aroundReceive(Actor.scala:467) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at akka.actor.ActorCell.invoke(ActorCell.scala:487) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at akka.dispatch.Mailbox.run(Mailbox.scala:220) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]

> Caused  by: java.lang.IllegalArgumentException: checkLocalJobRunnerConfiguration: When using LocalJobRunner, must have only one worker since only 1 task at a time!
at org.apache.giraph.job.GiraphJob.checkLocalJobRunnerConfiguration(GiraphJob.java:162) ~[graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at org.apache.giraph.job.GiraphJob.run(GiraphJob.java:236) ~[graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at science.atlarge.graphalytics.giraph.GiraphJob.run(GiraphJob.java:233) ~[graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70) ~[hadoop-common-2.7.7.jar:?]
at science.atlarge.graphalytics.giraph.GiraphPlatform.run(GiraphPlatform.java:244) ~[graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
... 14 more

> My giraph platform properties：
#The platform
platform.name = Giraph
platform.acronym = giraph
platform.version = 1.2.0
platform.link = https://github.com/apache/giraph
#Address of ZooKeeper deployment (required)
platform.giraph.zoo-keeper-address: centos6:2181,centos7:2181,centos8:2181,centos9:2181,centos10:2181
#Number of Giraph workers (default: 1)
platform.giraph.job.worker-count: 4
#Size of the total memory used per Giraph worker in MB (default: 1280)
platform.giraph.job.memory-size: 4096
#Size of the heap used per Giraph worker in MB, rounded down to the nearest GB by Giraph (default: 1024)
platform.giraph.job.heap-size: 2048
#Number of cores per Giraph worker (default: 1)
platform.giraph.job.worker-cores: 6
#Root directory of Hadoop framework, i.e. HADOOP_HOME (required)
platform.hadoop.home: /home/zc/dy/hadoop-2.7.7
#Directory on HDFS to store all input and output of Graphalytics jobs in
platform.hadoop.hdfs.directory: /ldbc/giraph
#Options starting of the form "platform.giraph.options.X" are passed on to Giraph as "giraph.X". For example:
#platform.giraph.options.numComputeThreads: 4
#platform.giraph.options.dns.namesever: default
#platform.giraph.options.preferIP: false
#platform.giraph.options.dns.interface: ib0
#platform.giraph.options.userPartitionCount: 4

I don't know where cause the error .My worker count is set 4.

**Comment by amusaafir** [comment]
Hello,

1. We're currently running Spark within a specific version of YARN. If you want to use a different version, you'll have to change that in the platform accordingly and recompile it again. However, we haven't tested this ourselves yet. 

2. It appears that Giraph can not find the Hadoop cluster. The `platform.giraph.zoo-keeper-address` property should be set to only _one_ value (the one from your master node), e.g., `platform.giraph.zoo-keeper-address: centos6:2181`.
If that doesn't work, can you try to set up Giraph using the [Graphalytics installer](https://graphalytics.org/software) and set the configuration from there? Do you get the same error?

**Comment by DioCin** [comment]
Hi,@amusaafir .
When i using the Graphalytics installer and set the same configuration.
I found the same error:

> Algorithm "Breadth first search" on graph "example-directed failed to complete:
science.atlarge.graphalytics.execution.PlatformExecutionException: Giraph job failed with exception: 
        at science.atlarge.graphalytics.giraph.GiraphPlatform.run(GiraphPlatform.java:256) ~[graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at science.atlarge.graphalytics.execution.BenchmarkRunner.run(BenchmarkRunner.java:113) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at science.atlarge.graphalytics.execution.RunnerService.onReceive(RunnerService.java:148) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]

> Caused by: java.lang.IllegalArgumentException: checkLocalJobRunnerConfiguration: When using LocalJobRunner, must have only one worker since only 1 task at a time!
        at org.apache.giraph.job.GiraphJob.checkLocalJobRunnerConfiguration(GiraphJob.java:162) ~[graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at org.apache.giraph.job.GiraphJob.run(GiraphJob.java:236) ~[graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at science.atlarge.graphalytics.giraph.GiraphJob.run(GiraphJob.java:233) ~[graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70) ~[hadoop-common-2.5.1.jar:?]
        at science.atlarge.graphalytics.giraph.GiraphPlatform.run(GiraphPlatform.java:244) ~[graphalytics-platforms-giraph-0.2-SNAPSHOT-default.jar:?]
        ... 14 more


My  platform configuration：
> platform.hadoop.home: /home/zc/dy/hadoop-2.5.1
platform.giraph.zoo-keeper-address: 192.168.4.26:2181
platform.giraph.job.heap-size: 2048
platform.giraph.job.memory-size: 4096
platform.giraph.job.worker-count: 4
platform.giraph.job.worker-cores: 6
platform.hadoop.hdfs.directory: /ldbc/giraph

I think the solution is that I should configure  giraph.SplitMasterWorker=true.. But I don't know where can I configure  this?

**Comment by amusaafir** [comment]
I will try to run the benchmark using the same version of Hadoop as you. I'll get back to you soon.

**Comment by DioCin** [comment]
@amusaafir  can you run the benchmark using the same version of Hadoop as me? Can you run giraph benchmark using platform.giraph.job.worker-count >1 ?
